FROM node:alpine

USER node

#  This will prevent a permissions issue
# since WORKDIR by default will create
# a directory if it does not exist and set
# ownership to root.
RUN mkdir -p /home/node/app
WORKDIR /home/node/app

COPY --chown=node:node ./package.json ./

RUN npm install

COPY --chown=node:node . .

CMD ["npm", "run", "start"]
